(rule (target "isp_012_float_interval.0.err.oracle") (mode fallback) (action (write-file "isp_012_float_interval.0.err.oracle" "")))
(rule (target "isp_012_float_interval.0.res.oracle") (mode fallback) (action (write-file "isp_012_float_interval.0.res.oracle" "")))
(rule (target "isp_046_nested_array_struct_unsupported.0.err.oracle") (mode fallback) (action (write-file "isp_046_nested_array_struct_unsupported.0.err.oracle" "")))
(rule (target "isp_046_nested_array_struct_unsupported.0.res.oracle") (mode fallback) (action (write-file "isp_046_nested_array_struct_unsupported.0.res.oracle" "")))
(rule (target "isp_041_repeated_pointer_mutation.0.err.oracle") (mode fallback) (action (write-file "isp_041_repeated_pointer_mutation.0.err.oracle" "")))
(rule (target "isp_041_repeated_pointer_mutation.0.res.oracle") (mode fallback) (action (write-file "isp_041_repeated_pointer_mutation.0.res.oracle" "")))
(rule (target "isp_001_entry_point.0.err.oracle") (mode fallback) (action (write-file "isp_001_entry_point.0.err.oracle" "")))
(rule (target "isp_001_entry_point.0.res.oracle") (mode fallback) (action (write-file "isp_001_entry_point.0.res.oracle" "")))
(rule (target "isp_053_global_annotations_warn.0.err.oracle") (mode fallback) (action (write-file "isp_053_global_annotations_warn.0.err.oracle" "")))
(rule (target "isp_053_global_annotations_warn.0.res.oracle") (mode fallback) (action (write-file "isp_053_global_annotations_warn.0.res.oracle" "")))
(rule (target "isp_019_set_lval_eval.0.err.oracle") (mode fallback) (action (write-file "isp_019_set_lval_eval.0.err.oracle" "")))
(rule (target "isp_019_set_lval_eval.0.res.oracle") (mode fallback) (action (write-file "isp_019_set_lval_eval.0.res.oracle" "")))
(rule (target "isp_011_float_interval.0.err.oracle") (mode fallback) (action (write-file "isp_011_float_interval.0.err.oracle" "")))
(rule (target "isp_011_float_interval.0.res.oracle") (mode fallback) (action (write-file "isp_011_float_interval.0.res.oracle" "")))
(rule (target "isp_027_array_data_structures.0.err.oracle") (mode fallback) (action (write-file "isp_027_array_data_structures.0.err.oracle" "")))
(rule (target "isp_027_array_data_structures.0.res.oracle") (mode fallback) (action (write-file "isp_027_array_data_structures.0.res.oracle" "")))
(rule (target "isp_034_manipulated_pointer_crashes.0.err.oracle") (mode fallback) (action (write-file "isp_034_manipulated_pointer_crashes.0.err.oracle" "")))
(rule (target "isp_034_manipulated_pointer_crashes.0.res.oracle") (mode fallback) (action (write-file "isp_034_manipulated_pointer_crashes.0.res.oracle" "")))
(rule (target "isp_051_unbounded_index.0.err.oracle") (mode fallback) (action (write-file "isp_051_unbounded_index.0.err.oracle" "")))
(rule (target "isp_051_unbounded_index.0.res.oracle") (mode fallback) (action (write-file "isp_051_unbounded_index.0.res.oracle" "")))
(rule (target "isp_054_index_expansion_below_limit.0.err.oracle") (mode fallback) (action (write-file "isp_054_index_expansion_below_limit.0.err.oracle" "")))
(rule (target "isp_054_index_expansion_below_limit.0.res.oracle") (mode fallback) (action (write-file "isp_054_index_expansion_below_limit.0.res.oracle" "")))
(rule (target "isp_055_negative_index_interval.0.err.oracle") (mode fallback) (action (write-file "isp_055_negative_index_interval.0.err.oracle" "")))
(rule (target "isp_055_negative_index_interval.0.res.oracle") (mode fallback) (action (write-file "isp_055_negative_index_interval.0.res.oracle" "")))
(rule (target "isp_021_struct.0.err.oracle") (mode fallback) (action (write-file "isp_021_struct.0.err.oracle" "")))
(rule (target "isp_021_struct.0.res.oracle") (mode fallback) (action (write-file "isp_021_struct.0.res.oracle" "")))
(rule (target "isp_022_pointers.0.err.oracle") (mode fallback) (action (write-file "isp_022_pointers.0.err.oracle" "")))
(rule (target "isp_022_pointers.0.res.oracle") (mode fallback) (action (write-file "isp_022_pointers.0.res.oracle" "")))
(rule (target "isp_056_cross_zero_index_interval.0.err.oracle") (mode fallback) (action (write-file "isp_056_cross_zero_index_interval.0.err.oracle" "")))
(rule (target "isp_056_cross_zero_index_interval.0.res.oracle") (mode fallback) (action (write-file "isp_056_cross_zero_index_interval.0.res.oracle" "")))
(rule (target "isp_008_interface_spec.0.err.oracle") (mode fallback) (action (write-file "isp_008_interface_spec.0.err.oracle" "")))
(rule (target "isp_008_interface_spec.0.res.oracle") (mode fallback) (action (write-file "isp_008_interface_spec.0.res.oracle" "")))
(rule (target "isp_006_mut_glob_nested_fn.0.err.oracle") (mode fallback) (action (write-file "isp_006_mut_glob_nested_fn.0.err.oracle" "")))
(rule (target "isp_006_mut_glob_nested_fn.0.res.oracle") (mode fallback) (action (write-file "isp_006_mut_glob_nested_fn.0.res.oracle" "")))
(rule (target "isp_026_return_global.0.err.oracle") (mode fallback) (action (write-file "isp_026_return_global.0.err.oracle" "")))
(rule (target "isp_026_return_global.0.res.oracle") (mode fallback) (action (write-file "isp_026_return_global.0.res.oracle" "")))
(rule (target "isp_016_if_nested.0.err.oracle") (mode fallback) (action (write-file "isp_016_if_nested.0.err.oracle" "")))
(rule (target "isp_016_if_nested.0.res.oracle") (mode fallback) (action (write-file "isp_016_if_nested.0.res.oracle" "")))
(rule (target "isp_023_fn_args_pbv_failing.0.err.oracle") (mode fallback) (action (write-file "isp_023_fn_args_pbv_failing.0.err.oracle" "")))
(rule (target "isp_023_fn_args_pbv_failing.0.res.oracle") (mode fallback) (action (write-file "isp_023_fn_args_pbv_failing.0.res.oracle" "")))
(rule (target "isp_005_mutated_globals.0.err.oracle") (mode fallback) (action (write-file "isp_005_mutated_globals.0.err.oracle" "")))
(rule (target "isp_005_mutated_globals.0.res.oracle") (mode fallback) (action (write-file "isp_005_mutated_globals.0.res.oracle" "")))
(rule (target "isp_009_array.0.err.oracle") (mode fallback) (action (write-file "isp_009_array.0.err.oracle" "")))
(rule (target "isp_009_array.0.res.oracle") (mode fallback) (action (write-file "isp_009_array.0.res.oracle" "")))
(rule (target "isp_039_pointer_struct_limits.0.err.oracle") (mode fallback) (action (write-file "isp_039_pointer_struct_limits.0.err.oracle" "")))
(rule (target "isp_039_pointer_struct_limits.0.res.oracle") (mode fallback) (action (write-file "isp_039_pointer_struct_limits.0.res.oracle" "")))
(rule (target "isp_028_thesis_example.0.err.oracle") (mode fallback) (action (write-file "isp_028_thesis_example.0.err.oracle" "")))
(rule (target "isp_028_thesis_example.0.res.oracle") (mode fallback) (action (write-file "isp_028_thesis_example.0.res.oracle" "")))
(rule (target "isp_050_index_expansion_too_wide.0.err.oracle") (mode fallback) (action (write-file "isp_050_index_expansion_too_wide.0.err.oracle" "")))
(rule (target "isp_050_index_expansion_too_wide.0.res.oracle") (mode fallback) (action (write-file "isp_050_index_expansion_too_wide.0.res.oracle" "")))
(rule (target "isp_002_unreachable.0.err.oracle") (mode fallback) (action (write-file "isp_002_unreachable.0.err.oracle" "")))
(rule (target "isp_002_unreachable.0.res.oracle") (mode fallback) (action (write-file "isp_002_unreachable.0.res.oracle" "")))
(rule (target "isp_010_enum_typedef.0.err.oracle") (mode fallback) (action (write-file "isp_010_enum_typedef.0.err.oracle" "")))
(rule (target "isp_010_enum_typedef.0.res.oracle") (mode fallback) (action (write-file "isp_010_enum_typedef.0.res.oracle" "")))
(rule (target "isp_007_interface_spec.0.err.oracle") (mode fallback) (action (write-file "isp_007_interface_spec.0.err.oracle" "")))
(rule (target "isp_007_interface_spec.0.res.oracle") (mode fallback) (action (write-file "isp_007_interface_spec.0.res.oracle" "")))
(rule (target "isp_035_init_struct.0.err.oracle") (mode fallback) (action (write-file "isp_035_init_struct.0.err.oracle" "")))
(rule (target "isp_035_init_struct.0.res.oracle") (mode fallback) (action (write-file "isp_035_init_struct.0.res.oracle" "")))
(rule (target "isp_025_fn_args_pbv_if_failing.0.err.oracle") (mode fallback) (action (write-file "isp_025_fn_args_pbv_if_failing.0.err.oracle" "")))
(rule (target "isp_025_fn_args_pbv_if_failing.0.res.oracle") (mode fallback) (action (write-file "isp_025_fn_args_pbv_if_failing.0.res.oracle" "")))
(rule (target "isp_033_nested_pointers_crashes.0.err.oracle") (mode fallback) (action (write-file "isp_033_nested_pointers_crashes.0.err.oracle" "")))
(rule (target "isp_033_nested_pointers_crashes.0.res.oracle") (mode fallback) (action (write-file "isp_033_nested_pointers_crashes.0.res.oracle" "")))
(rule (target "isp_017_cast.0.err.oracle") (mode fallback) (action (write-file "isp_017_cast.0.err.oracle" "")))
(rule (target "isp_017_cast.0.res.oracle") (mode fallback) (action (write-file "isp_017_cast.0.res.oracle" "")))
(rule (target "isp_043_missing_helper_contract_duplicate_b.0.err.oracle") (mode fallback) (action (write-file "isp_043_missing_helper_contract_duplicate_b.0.err.oracle" "")))
(rule (target "isp_043_missing_helper_contract_duplicate_b.0.res.oracle") (mode fallback) (action (write-file "isp_043_missing_helper_contract_duplicate_b.0.res.oracle" "")))
(rule (target "isp_057_declared_array_extent_mismatch.0.err.oracle") (mode fallback) (action (write-file "isp_057_declared_array_extent_mismatch.0.err.oracle" "")))
(rule (target "isp_057_declared_array_extent_mismatch.0.res.oracle") (mode fallback) (action (write-file "isp_057_declared_array_extent_mismatch.0.res.oracle" "")))
(rule (target "isp_030_switch.0.err.oracle") (mode fallback) (action (write-file "isp_030_switch.0.err.oracle" "")))
(rule (target "isp_030_switch.0.res.oracle") (mode fallback) (action (write-file "isp_030_switch.0.res.oracle" "")))
(rule (target "isp_036_return_local_struct.0.err.oracle") (mode fallback) (action (write-file "isp_036_return_local_struct.0.err.oracle" "")))
(rule (target "isp_036_return_local_struct.0.res.oracle") (mode fallback) (action (write-file "isp_036_return_local_struct.0.res.oracle" "")))
(rule (target "isp_020_interval_lval_eval.0.err.oracle") (mode fallback) (action (write-file "isp_020_interval_lval_eval.0.err.oracle" "")))
(rule (target "isp_020_interval_lval_eval.0.res.oracle") (mode fallback) (action (write-file "isp_020_interval_lval_eval.0.res.oracle" "")))
(rule (target "isp_042_missing_helper_contract_report.0.err.oracle") (mode fallback) (action (write-file "isp_042_missing_helper_contract_report.0.err.oracle" "")))
(rule (target "isp_042_missing_helper_contract_report.0.res.oracle") (mode fallback) (action (write-file "isp_042_missing_helper_contract_report.0.res.oracle" "")))
(rule (target "isp_018_single_lval_eval.0.err.oracle") (mode fallback) (action (write-file "isp_018_single_lval_eval.0.err.oracle" "")))
(rule (target "isp_018_single_lval_eval.0.res.oracle") (mode fallback) (action (write-file "isp_018_single_lval_eval.0.res.oracle" "")))
(rule (target "isp_043_missing_helper_contract_duplicate_a.0.err.oracle") (mode fallback) (action (write-file "isp_043_missing_helper_contract_duplicate_a.0.err.oracle" "")))
(rule (target "isp_043_missing_helper_contract_duplicate_a.0.res.oracle") (mode fallback) (action (write-file "isp_043_missing_helper_contract_duplicate_a.0.res.oracle" "")))
(rule (target "isp_045_enum_indexed_struct.0.err.oracle") (mode fallback) (action (write-file "isp_045_enum_indexed_struct.0.err.oracle" "")))
(rule (target "isp_045_enum_indexed_struct.0.res.oracle") (mode fallback) (action (write-file "isp_045_enum_indexed_struct.0.res.oracle" "")))
(rule (target "isp_004_accessed_globals.0.err.oracle") (mode fallback) (action (write-file "isp_004_accessed_globals.0.err.oracle" "")))
(rule (target "isp_004_accessed_globals.0.res.oracle") (mode fallback) (action (write-file "isp_004_accessed_globals.0.res.oracle" "")))
(rule (target "isp_037_return_global_struct.0.err.oracle") (mode fallback) (action (write-file "isp_037_return_global_struct.0.err.oracle" "")))
(rule (target "isp_037_return_global_struct.0.res.oracle") (mode fallback) (action (write-file "isp_037_return_global_struct.0.res.oracle" "")))
(rule (target "isp_014_if.0.err.oracle") (mode fallback) (action (write-file "isp_014_if.0.err.oracle" "")))
(rule (target "isp_014_if.0.res.oracle") (mode fallback) (action (write-file "isp_014_if.0.res.oracle" "")))
(rule (target "isp_052_pure_logic_definitions.0.err.oracle") (mode fallback) (action (write-file "isp_052_pure_logic_definitions.0.err.oracle" "")))
(rule (target "isp_052_pure_logic_definitions.0.res.oracle") (mode fallback) (action (write-file "isp_052_pure_logic_definitions.0.res.oracle" "")))
(rule (target "isp_038_struct_as_arg.0.err.oracle") (mode fallback) (action (write-file "isp_038_struct_as_arg.0.err.oracle" "")))
(rule (target "isp_038_struct_as_arg.0.res.oracle") (mode fallback) (action (write-file "isp_038_struct_as_arg.0.res.oracle" "")))
(rule (target "isp_013_float_single.0.err.oracle") (mode fallback) (action (write-file "isp_013_float_single.0.err.oracle" "")))
(rule (target "isp_013_float_single.0.res.oracle") (mode fallback) (action (write-file "isp_013_float_single.0.res.oracle" "")))
(rule (target "isp_048_enum_indexed_struct_fields.0.err.oracle") (mode fallback) (action (write-file "isp_048_enum_indexed_struct_fields.0.err.oracle" "")))
(rule (target "isp_048_enum_indexed_struct_fields.0.res.oracle") (mode fallback) (action (write-file "isp_048_enum_indexed_struct_fields.0.res.oracle" "")))
(rule (target "isp_000_eva_over_aproximation.0.err.oracle") (mode fallback) (action (write-file "isp_000_eva_over_aproximation.0.err.oracle" "")))
(rule (target "isp_000_eva_over_aproximation.0.res.oracle") (mode fallback) (action (write-file "isp_000_eva_over_aproximation.0.res.oracle" "")))
(rule (target "isp_049_index_expansion_limit.0.err.oracle") (mode fallback) (action (write-file "isp_049_index_expansion_limit.0.err.oracle" "")))
(rule (target "isp_049_index_expansion_limit.0.res.oracle") (mode fallback) (action (write-file "isp_049_index_expansion_limit.0.res.oracle" "")))
(rule (target "isp_040_conditional_pointer_mutation.0.err.oracle") (mode fallback) (action (write-file "isp_040_conditional_pointer_mutation.0.err.oracle" "")))
(rule (target "isp_040_conditional_pointer_mutation.0.res.oracle") (mode fallback) (action (write-file "isp_040_conditional_pointer_mutation.0.res.oracle" "")))
(rule (target "isp_003_helper.0.err.oracle") (mode fallback) (action (write-file "isp_003_helper.0.err.oracle" "")))
(rule (target "isp_003_helper.0.res.oracle") (mode fallback) (action (write-file "isp_003_helper.0.res.oracle" "")))
(rule (target "isp_047_constant_indexed_struct_fields.0.err.oracle") (mode fallback) (action (write-file "isp_047_constant_indexed_struct_fields.0.err.oracle" "")))
(rule (target "isp_047_constant_indexed_struct_fields.0.res.oracle") (mode fallback) (action (write-file "isp_047_constant_indexed_struct_fields.0.res.oracle" "")))
(rule (target "isp_024_fn_args_pbv_unused.0.err.oracle") (mode fallback) (action (write-file "isp_024_fn_args_pbv_unused.0.err.oracle" "")))
(rule (target "isp_024_fn_args_pbv_unused.0.res.oracle") (mode fallback) (action (write-file "isp_024_fn_args_pbv_unused.0.res.oracle" "")))
(rule (target "isp_015_if.0.err.oracle") (mode fallback) (action (write-file "isp_015_if.0.err.oracle" "")))
(rule (target "isp_015_if.0.res.oracle") (mode fallback) (action (write-file "isp_015_if.0.res.oracle" "")))
(rule (target "isp_029_read_array.0.err.oracle") (mode fallback) (action (write-file "isp_029_read_array.0.err.oracle" "")))
(rule (target "isp_029_read_array.0.res.oracle") (mode fallback) (action (write-file "isp_029_read_array.0.res.oracle" "")))
(rule (target "isp_032_array_index_processing.0.err.oracle") (mode fallback) (action (write-file "isp_032_array_index_processing.0.err.oracle" "")))
(rule (target "isp_032_array_index_processing.0.res.oracle") (mode fallback) (action (write-file "isp_032_array_index_processing.0.res.oracle" "")))

