FRAMAC_SHARE := $(shell frama-c-config -print-share-path)
PLUGIN_NAME = Isp
PLUGIN_CMO = isp_options isp_utils isp_local_states isp_emitters isp_visitor isp_main
PLUGIN_TESTS_DIRS := isp
include $(FRAMAC_SHARE)/Makefile.dynamic